### ISSUE TITLE
易语言提示缺少符号 __iob、___argv、___argc、__mbctype

### ISSUE THREAD

**Issue by monlove** [Chuyu-Team/VC-LTL5#13]

**Comment by mingkuang-Chuyu** [comment]
VC-LTL是基于MD的，所以默认没有这些符号，这是设计如此。这个问题的背景是易语言，易语言似乎只能使用MT。

**Comment by mingkuang-Chuyu** [comment]
这个问题需要确认他们是否是常量，如果是，那么我导出一份副本就可以解决……如果不是，那么我就只能关闭，作为无效反馈处理。

**Comment by mingkuang-Chuyu** [comment]
_iob 它是一个数组，所以以目前的技术无法提供 __iob 这样的符号
 
```cpp
extern FILE _iob[];
```

我建议你联系易语言开发组，提供一种md的选项或者其他的吧……

**Comment by monlove** [comment]
好的，谢谢
