### ISSUE TITLE
a bug somewhere that makes heap corrupted I don't know xD

### ISSUE THREAD

**Issue by gurachan** [Chuyu-Team/VC-LTL5#15]
![image](https://user-images.githubusercontent.com/12135498/142785182-e63f5a3e-3c06-4f28-86e5-faa70369221d.png)

I'm using vs2022 whenever I switch on this heap corrupt is automatically xD but if I remove it.. it works fine.

I'm using windows 10 2004

**Comment by mingkuang-Chuyu** [comment]
Please provide the code.

**Comment by gurachan** [comment]
> Please provide the code and VC-LTL configuration information.
> 
> VC-LTL Version? VC-LTL 5.1 mode or 6.1 mode or Win10 mode ? x86 or x64 or arm64?

VC-LTL Version 5.0.1. both x86 and64, yes I'm using windows 10.

I'm using vs2022 .. and installing it via NuGet.

**Comment by mingkuang-Chuyu** [comment]
> > Please provide the code and VC-LTL configuration information.
> > VC-LTL Version? VC-LTL 5.1 mode or 6.1 mode or Win10 mode ? x86 or x64 or arm64?
> 
> VC-LTL Version 5.0.1. both x86 and64, yes I'm using windows 10.
> 
> I'm using vs2022 .. and installing it via NuGet.

VC-LTL 5.1 mode or 6.1 mode or Win10 mode ?

ANd please provide the code to reproduce the problem.

**Comment by mingkuang-Chuyu** [comment]
如果7天后仍然没有提供有效的信息，我会关闭问题

**Comment by mingkuang-Chuyu** [comment]
长期无人应答，关闭问题
