### ISSUE TITLE
使用5.01 beta3版本编译时会导致IsBadPtr()一直触发断点异常

### ISSUE THREAD

**Issue by luciouskami** [Chuyu-Team/VC-LTL5#17]
如题

**Comment by MouriNaruto** [comment]
5.0.1-Beta3 是啥年代的版本了

**Comment by mingkuang-Chuyu** [comment]
请提供复现代码，以及详细的信息，
比如，目标平台是什么，5.1，还是6.1……
目标体系是什么，x86 或者 x64 还是……

**Comment by mingkuang-Chuyu** [comment]
1. 问题不明确 Windows没有IsBadPtr这个函数，只有IsBadRead 或者 Wirte，此外 `5.01 beta3` 是指 `5.0.1-beta3` 还是指 `5.0.3-beta1` ? 

2. 信息不全，VC-LTL明明输出了大量的Info，但是反馈者并没有复制这些信息，内容只有简单的一个 如题。
3. 未提供复现代码，即使是 IsBadRead 或者 Wirte，本地并没有任何问题。

所以关闭此问题，除非提供更多有价值的信息

**Comment by luciouskami** [comment]
将提供更多有效的信息
