### ISSUE TITLE
tlsGuards导致无法与老版本CRT链接

### ISSUE THREAD

**Issue by ntp2000** [Chuyu-Team/VC-LTL5#21]
开发环境： VS2017 15.9.11
VC-LTL5版本: 5.0.4beta1
编译过程：1.下载vc-ltl binary，解压缩后执行instal.cmd

                  2.下载qt 5.12.12 代码，修改qtbase/mkspecs/common/msvc-desktop.conf
-QMAKE_CFLAGS_RELEASE    = $$QMAKE_CFLAGS_OPTIMIZE -MD
-QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_OPTIMIZE -Zi -MD
-QMAKE_CFLAGS_DEBUG      = -Zi -MDd
+QMAKE_CFLAGS_RELEASE    = $$QMAKE_CFLAGS_OPTIMIZE -MT
+QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_OPTIMIZE -Zi -MT
+QMAKE_CFLAGS_DEBUG      = -Zi -MTd

                 3. 打开vc2017 x64命令行
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.11
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'      
          
                 4. 执行VC-LTL helper for nmake.cmd
#######################################################################
#                                                                     #
#     *         *      * *             *        * * * * *  *          #
#      *       *     *                 *            *      *          #
#       *     *     *       * * * * *  *            *      *          #
#        *   *       *                 *            *      *          #
#          *           * *             * * * *      *      * * * *    #
#                                                                     #
#######################################################################
VC-LTL Path : c:\Users\SunAC\Downloads\vc-ltl\
VC Tools Version : 14.16.27023
WindowsTargetPlatformMinVersion : 6.0.6000.0
Platform : x64
                 
                 5.   进入qt代码目录，配置编译
configure -confirm-license -opensource -prefix C:\QtSDK\qt-5.12.12-x64-vc2017 -release -force-debug-info -separate-debug-info -qml-debug -platform win32-msvc -mp -opengl dynamic -qt-zlib -qt-libpng -qt-libjpeg -plugin-sql-odbc -plugin-sql-mysql -plugin-sql-oci -plugin-sql-psql -no-compile-examples -nomake tests -no-icu -webengine-proprietary-codecs

报错：
 link  /OUT:..\bin\qmake.exe project.obj main.obj ioutils.obj proitems.obj qmakevfs.obj  ........
libvcruntime.lib(frame.obj) : error LNK2019: 无法解析的外部符号 __dyn_tls_on_demand_init，该符号在函数 "public: static void * __cdecl __FrameHandler4::CxxCallCatchBlock(struct _EXCEPTION_RECORD *)" (?CxxCallCatchBlock@__FrameHandler4@@SAPEAXPEAU_EXCEPTION_RECORD@@@Z) 中被引用
libvcruntime.lib(frame.obj) : error LNK2001: 无法解析的外部符号 __tls_guard
..\bin\qmake.exe : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"”: 返回代码“0x460”
Stop.

**Comment by mingkuang-Chuyu** [comment]
https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements-2019?view=msvc-170#tls-guard-changes
```
TLS Guard changes
Previously, thread-local variables in DLLs weren't correctly initialized. Other than on the thread that loaded the DLL, they weren't initialized before first use on threads that existed before the DLL was loaded. This defect has now been corrected. Thread-local variables in such a DLL get initialized immediately before their first use on such threads.

This new behavior of testing for initialization on uses of thread-local variables may be disabled by using the /Zc:tlsGuards- compiler option. Or, by adding the [[msvc:no_tls_guard]] attribute to particular thread local variables.
```

由于2019更新了此功能，所以发生了这个问题，由于 VC_LTL_UCRT_CatchStateInParent 线程局部存储并不需要这种特性，而且VC-LTL其他代码也本身就做了保证，可以直接禁用此功能来进行兼容性修正。

**Comment by mingkuang-Chuyu** [comment]
另外注意，VC-LTL 4.0 原本没有这个问题，是因为添加了 `/Zc:tlsGuards-`，但是到了5.0，这个选项在迁徙过程中丢失。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/actions/runs/1609904453

下载式用一下，我查看了 obj，已经没有想过依赖了。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.0.4-Beta2
