### ISSUE TITLE
VC-LTL 在 Debug 模式下 ASAN 无法使用 

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/VC-LTL5#22]
ASAN 即 Address Sanitizer，详细介绍可参阅 https://docs.microsoft.com/en-us/cpp/sanitizers/asan

这个功能对于一些用户来说还是很有用的，该问题由友人 @FASTSHIFT 发现在使用了 VC-LTL 的 LVGL Windows 仿真器项目无法使用 ASAN 后，我进行粗略分析后做出的反馈

注：由于 Release 模式下可以正常使用 ASAN，于是猜测和 VC-LTL 的 Debug Heap 实现有关

附报错截图一份

![image](https://user-images.githubusercontent.com/10867563/146859001-737ab40a-84b2-4a4d-a03a-28f665ad043d.png)

复现参考环境

- MSVC 2022 (14.30.30705)
- VC-LTL v5.0.4-Beta1

毛利

**Comment by mingkuang-Chuyu** [comment]
确认Release没有问题

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/tree/ASAN_Debug_support
分支中跟踪此问题

**Comment by mingkuang-Chuyu** [comment]
在分支中，目前Debug可以编译通过，但是任然会有运行时报错。ASAN自身的Hook实现似乎有点问题。
