### ISSUE TITLE
VC-LTL5不能与VC2019配合使用编译Qt 5.12.12

### ISSUE THREAD

**Issue by ntp2000** [Chuyu-Team/VC-LTL5#23]
开发环境： VS2019 16.11.5 (cl 14.29.30133)
VC-LTL5版本: 5.0.4beta1
编译过程：1.下载vc-ltl binary，解压缩后执行instal.cmd
                  2.下载Qt 5.12.12,打补丁，使用/MT编译
                  3.打开vc2019 x64命令行
                vcvarsall.bat x64 10.0.19041.0 -vcvars_ver=14.29
                  4.设置Gnu工具路径
               set PATH=%PATH%;C:\QtSDK\GnuTools\Perl\bin;C:\QtSDK\GnuTools\Python27;C:\QtSDK\GnuTools\Ruby21\bin
                  5.执行VC-LTL helper for nmake.cmd
#######################################################################
#                                                                     #
#     *         *      * *             *        * * * * *  *          #
#      *       *     *                 *            *      *          #
#       *     *     *       * * * * *  *            *      *          #
#        *   *       *                 *            *      *          #
#          *           * *             * * * *      *      * * * *    #
#                                                                     #
#######################################################################
VC-LTL Path : C:\QtSDK\vc-ltl\
VC Tools Version : 14.29.30133
WindowsTargetPlatformMinVersion : 6.0.6000.0
Platform : x64
                  6.配置Qt编译选项
configure -confirm-license -opensource -prefix C:\QtSDK\qt-5.12.12-x64-vc2019 -release -force-debug-info -separate-debug-info -qml-debug -platform win32-msvc -mp -opengl dynamic -qt-zlib -qt-libpng -qt-libjpeg -no-compile-examples -nomake tests -no-icu
                 7.jom执行编译
报错
[1681/22547] cmd /c C:\QtSDK\GnuTools\Python27\python.exe ../../3rdparty/chromium/build/toolchain/win/tool_wrapper.py delete-file ./brotli.exe.pdb && C:\QtSDK\GnuTools\Python27\python.exe ../../3rdparty/chromium/build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /OUT:./brotli.exe /PDB:./brotli.exe.pdb @./brotli.exe.rsp
FAILED: brotli.exe brotli.exe.pdb
cmd /c C:\QtSDK\GnuTools\Python27\python.exe ../../3rdparty/chromium/build/toolchain/win/tool_wrapper.py delete-file ./brotli.exe.pdb && C:\QtSDK\GnuTools\Python27\python.exe ../../3rdparty/chromium/build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /OUT:./brotli.exe /PDB:./brotli.exe.pdb @./brotli.exe.rsp
libucrt.lib(setlocal_thunks.obj) : error LNK2001: 无法解析的外部符号 __imp__amsg_exit
.\brotli.exe : fatal error LNK1120: 1 个无法解析的外部命令

奇怪
libucrt.lib会链接到cdecl调用的函数么？   

附补丁：

diff -ur a/qtbase/mkspecs/common/msvc-desktop.conf b/qtbase/mkspecs/common/msvc-desktop.conf
--- a/qtbase/mkspecs/common/msvc-desktop.conf   2017-06-19 13:36:58 +0800
+++ b/qtbase/mkspecs/common/msvc-desktop.conf   2017-06-20 09:58:33 +0800
@@ -30,8 +30,8 @@
 QMAKE_CFLAGS            = -nologo -Zc:wchar_t
 QMAKE_CFLAGS_WARN_ON    = -W3
 QMAKE_CFLAGS_WARN_OFF   = -W0
-QMAKE_CFLAGS_RELEASE    = $$QMAKE_CFLAGS_OPTIMIZE -MD
-QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_OPTIMIZE -Zi -MD
-QMAKE_CFLAGS_DEBUG      = -Zi -MDd
+QMAKE_CFLAGS_RELEASE    = $$QMAKE_CFLAGS_OPTIMIZE -MT
+QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_OPTIMIZE -Zi -MT
+QMAKE_CFLAGS_DEBUG      = -Zi -MTd
 QMAKE_CFLAGS_YACC       =
 QMAKE_CFLAGS_LTCG       = -GL
diff -ur a/qtwebengine/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp b/qtwebengine/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp
--- a/qtwebengine/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp	2019-03-07 17:23:57 +0800
@@ -72,9 +72,9 @@
 {
      const RGB9E5Data *inputData = reinterpret_cast<const RGB9E5Data*>(&input);
 
-    *red = inputData->R * pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
-    *green = inputData->G * pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
-    *blue = inputData->B * pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
+    *red = inputData->R * (float)pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
+    *green = inputData->G * (float)pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
+    *blue = inputData->B * (float)pow(2.0f, (int)inputData->E - g_sharedexp_bias - g_sharedexp_mantissabits);
 }
 
 }  // namespace gl
diff -ur a/qtwebengine/src/3rdparty/chromium/build/config/BUILDCONFIG.gn b/qtwebengine/src/3rdparty/chromium/build/config/BUILDCONFIG.gn
--- a/qtwebengine/src/3rdparty/chromium/build/config/BUILDCONFIG.gn	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/build/config/BUILDCONFIG.gn	2019-03-27 14:05:29 +0800
@@ -545,7 +545,7 @@
 
 if (is_win) {
   default_compiler_configs += [
-    "//build/config/win:default_crt",
+    "//build/config/win:static_crt",
     "//build/config/win:lean_and_mean",
     "//build/config/win:nominmax",
     "//build/config/win:unicode",
diff -ur a/qtwebengine/src/3rdparty/chromium/build/config/win/BUILD.gn b/qtwebengine/src/3rdparty/chromium/build/config/win/BUILD.gn
--- a/qtwebengine/src/3rdparty/chromium/build/config/win/BUILD.gn	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/build/config/win/BUILD.gn	2019-03-27 16:47:54 +0800
@@ -218,7 +219,7 @@
   if (!use_vs_code_analysis) {
     # This is required for ATL to use XP-safe versions of its functions.
     # However it is prohibited when using /analyze
-    defines += [ "_USING_V110_SDK71_" ]
+    # defines += [ "_USING_V110_SDK71_" ]
   }
 
   if (use_custom_libcxx) {
diff -ur a/qtwebengine/src/3rdparty/chromium/third_party/breakpad/breakpad/src/build/common.gypi b/qtwebengine/src/3rdparty/chromium/third_party/breakpad/breakpad/src/build/common.gypi
--- a/qtwebengine/src/3rdparty/chromium/third_party/breakpad/breakpad/src/build/common.gypi	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/third_party/breakpad/breakpad/src/build/common.gypi	2019-03-27 16:27:47 +0800
@@ -323,7 +323,7 @@
           '_CRT_NONSTDC_NO_WARNINGS',
           '_CRT_NONSTDC_NO_DEPRECATE',
           # This is required for ATL to use XP-safe versions of its functions.
-          '_USING_V110_SDK71_',
+          # '_USING_V110_SDK71_',
         ],
         'msvs_disabled_warnings': [4800],
         'msvs_settings': {
diff -ur a/qtwebengine/src/3rdparty/chromium/third_party/brotli/BUILD.gn b/qtwebengine/src/3rdparty/chromium/third_party/brotli/BUILD.gn
--- a/qtwebengine/src/3rdparty/chromium/third_party/brotli/BUILD.gn	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/third_party/brotli/BUILD.gn	2019-03-27 14:07:15 +0800
@@ -170,7 +170,9 @@
     if (is_win && visual_studio_version == "2015") {
       # Disabling "result of 32-bit shift implicitly converted to 64 bits",
       # caused by code like: foo |= (1 << i);   // warning 4334
-      cflags = [ "/wd4334" ]
+      cflags = [ "/wd4334", "/MT" ]
+    } else {
+      cflags = [ "/MT" ]
     }
 
     # Always build release since this is a build tool.
diff -ur a/qtwebengine/src/3rdparty/chromium/third_party/yasm/BUILD.gn b/qtwebengine/src/3rdparty/chromium/third_party/yasm/BUILD.gn
--- a/qtwebengine/src/3rdparty/chromium/third_party/yasm/BUILD.gn	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/chromium/third_party/yasm/BUILD.gn	2019-03-27 16:20:45 +0800
@@ -49,8 +49,8 @@
   if (is_win) {
     # This switches to using the release CRT. On debug component builds of
     # highbd_sad4d_sse2.asm on Windows this saves about 15 s.
-    configs_to_delete += [ "//build/config/win:default_crt" ]
-    configs_to_add += [ "//build/config/win:release_crt" ]
+    # configs_to_delete += [ "//build/config/win:default_crt" ]
+    # configs_to_add += [ "//build/config/win:release_crt" ]
   }
 }
 
diff -ur a/qtwebengine/src/3rdparty/ninja/configure.py b/qtwebengine/src/3rdparty/ninja/configure.py
--- a/qtwebengine/src/3rdparty/ninja/configure.py	2019-03-07 17:23:57 +0800
+++ b/qtwebengine/src/3rdparty/ninja/configure.py	2019-03-27 14:04:40 +0800
@@ -305,7 +305,7 @@
               '/nologo',  # Don't print startup banner.
               '/Zi',  # Create pdb with debug info.
               '/W4',  # Highest warning level.
-              '/WX',  # Warnings as errors.
+#              '/WX',  # Warnings as errors.
               '/wd4530', '/wd4100', '/wd4706', '/wd4244',
               '/wd4512', '/wd4800', '/wd4702', '/wd4819',
               # Disable warnings about constant conditional expressions.
@@ -320,6 +320,8 @@
               '/wd4267',
               '/DNOMINMAX', '/D_CRT_SECURE_NO_WARNINGS',
               '/D_HAS_EXCEPTIONS=0',
+ 	      '/MT',
+ 	      '/D_DISABLE_DEPRECATE_LTL_MESSAGE',
               '/DNINJA_PYTHON="%s"' % options.with_python]
     if platform.msvc_needs_fs():
         cflags.append('/FS')

**Comment by ntp2000** [comment]
是ninja的锅，修改ninja配置就编译通过了

**Comment by mingkuang-Chuyu** [comment]
提问者说
在 qtwebengine/src/3rdparty/chromium/build/config/win/BUILD.gn文件中找到
libs_path 加入vcltl5 lib路径即可
