### ISSUE TITLE
不支持FH4异常处理的环境导致链接失败

### ISSUE THREAD

**Issue by ntp2000** [Chuyu-Team/VC-LTL5#24]
环境： VS2017 x64
编译： openssl 1.0.2u
命令：
perl Configure VC-WIN64A --prefix=C:\QtSDK\openssl-1.0.2u-x64
call ms\do_win64a
nmake -f ms\ntdll.mak
报错：
libucrt.lib(wcrtomb.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
out32dll\constant_time_test.exe : fatal error LNK1120: 1 unresolved externals

备注：VS2017 x86 ,VS 2019 x64/x86 均能正常编译通过。

**Comment by ntp2000** [comment]
报错的vcltl配置
VC-LTL Path : E:\QtSDK\vc-ltl\vc-ltl5\
VC Tools Version : 14.16.27023
WindowsTargetPlatformMinVersion : 5.2.3790.0
Platform : x64
[vcvarsall.bat] Environment initialized for: 'x64'


但如果设置MinVersion=6.0.6000.0可通过编译：
VC-LTL Path : E:\QtSDK\vc-ltl\vc-ltl5\
VC Tools Version : 14.16.27023
WindowsTargetPlatformMinVersion : 6.0.6000.0
Platform : x64
[vcvarsall.bat] Environment initialized for: 'x64'

x86下均可通过编译。

**Comment by ntp2000** [comment]
经测试已经可以通过编译了

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.0.4-Beta2
