### ISSUE TITLE
找不到符号__dyn_tls_on_demand_init，__tls_guard

### ISSUE THREAD

**Issue by squirrelfish** [Chuyu-Team/VC-LTL5#28]
1>libvcruntime.lib(frame.obj) : error LNK2001: 无法解析的外部符号 __dyn_tls_on_demand_init
1>libvcruntime.lib(frame.obj) : error LNK2001: 无法解析的外部符号 __tls_guard

**Comment by MouriNaruto** [comment]
请提供你使用的 VC-LTL、Windows SDK 和 MSVC 工具链的版本信息

毛利

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/issues/21
重复问题，并且 v5.0.4-Beta2 以及修复
