### ISSUE TITLE
启用 /guard:ehcont 时编译报告2047链接错误

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/VC-LTL5#31]
`/guard:ehcont` 选项介绍：https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-eh-continuation-metadata?view=msvc-170

前段日子，有人为 NanaZip 贡献了 CET 和 CFG 的支持，在验证的时候发现 VC-LTL 的 UCRT 实现未适配 `/guard:ehcont` 编译器选项支持

毛利

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/179359406-7863ccb8-b577-495d-b546-dc4d1847931f.png)

附相关问题截图

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.0.6-Beta1
请帮忙验证

**Comment by MouriNaruto** [comment]
突然发现忘记在这里说了，做个补充

经过前段日子验证，NanaZip 附带相关选项成功编译且暂时没有发现奇怪的问题

于是 Nana 系列项目用的编译工具链最近开始会启用相关选项

毛利
