### ISSUE TITLE
分享一下实际使用的体验以及对适用场景的分析（非bug）

### ISSUE THREAD

**Issue by Demonese** [Chuyu-Team/VC-LTL5#33]
实际使用下来，我发现链接到msvcrt的好处在编写短小的命令行程序的时候很有效，这时候因为软件的体积本身就比较小，静态链接msvc运行库增加的体积就特别明显。

但是一旦使用到比较庞大的软件上，而且不带一堆第三方动态库，而是全部静态链接到一起，体积也只能减少200到300KB，软件自身的体量就占大头了。

所以我认为VC-LTL适用的场景应该是：
* 携带大量dll形式的第三方库的软件，如果每一个dll都静态链接msvc运行库上去，那么体积增长会十分可观，这时候全部使用VC-LTL，可以获得最大的收益
* 短小的命令行应用程序，静态链接msvc运行库带来的体积膨胀显著

**Comment by mingkuang-Chuyu** [comment]
感谢你的支持，因为不是Bug，所以我将关闭它。
