### ISSUE TITLE
VC-LTL不兼容 Intel C++ Compiler 2022 工具集

### ISSUE THREAD

**Issue by icls1337** [Chuyu-Team/VC-LTL5#37]
warning LTL2003: VC-LTL不兼容 Intel C++ Compiler 2022 工具集，请切换到 Visual Studio 2015/2017/2019/2022 然后继续。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/commit/13d5af4848acfa55ed03b01d30816f924791e154
已经合入
