### ISSUE TITLE
Win10 + VS2022 + CMake, Error

### ISSUE THREAD

**Issue by dbyoung720** [Chuyu-Team/VC-LTL5#39]
CMake Error:    
  VC-LTL not load, because CMAKE_SYSTEM_NAME is not defined!!!
  Call Stack (most recent call first):
  VC-LTL helper for cmake.cmake:87 (include)
  CMakeLists.txt:19 (include)

**Comment by dbyoung720** [comment]
Moreover, CUDA compilation is automatically removed.
Without VC-LTL5, there is no such problem.

**Comment by mingkuang-Chuyu** [comment]
More information is needed, for example, a sample project. 
After all, CMake has many ways to use it, and I haven't used CUDA...

**Comment by mingkuang-Chuyu** [comment]
@dbyoung720  Help.

**Comment by mingkuang-Chuyu** [comment]
缺乏关键信息，无法跟进。
