### ISSUE TITLE
添加xmake的编译支持？

### ISSUE THREAD

**Issue by MiFeng-super** [Chuyu-Team/VC-LTL5#42]
xmake: https://xmake.io/#/

**Comment by mingkuang-Chuyu** [comment]
长期未回复。关闭新功能建议，如果未来有xmake志愿者，则可以重新打开此功能。

**Comment by star-hengxing** [comment]
我已经打包到 xmake 的官方包管理上：https://github.com/xmake-io/xmake-repo/pull/2056
