### ISSUE TITLE
System-Dlls strings

### ISSUE THREAD

**Issue by BitBlit88** [Chuyu-Team/VC-LTL5#44]
When I build a project using vc-LTL5 with target version 5 or 6 there are still some leftover strings in the rdata-section of the binary pointing to some system dlls:

api-ms-win-core-datetime-l1-1-1 
api-ms-win-core-fibers-l1-1-1 
api-ms-win-core-file-l1-2-2 
api-ms-win-core-localization-l1-2-1 
api-ms-win-core-localization-obsolete-l1-2-0 
api-ms-win-core-processthreads-l1-1-2 
api-ms-win-core-string-l1-1-0 
api-ms-win-core-synch-l1-2-0 
api-ms-win-core-sysinfo-l1-2-1 
api-ms-win-core-winrt-l1-1-0 
api-ms-win-core-xstate-l2-1-0 
api-ms-win-rtcore-ntuser-window-l1-1-0 
api-ms-win-security-systemfunctions-l1-1-0 
ext-ms-win-ntuser-dialogbox-l1-1-0 
ext-ms-win-ntuser-windowstation-l1-1-0 
api-ms-win-appmodel-runtime-l1-1-2

These are no direct dependencies, they are only utf16 strings in the data section occupying more than 1KB.
Using target version 10 with a dependency to ucrt, there are no such strings.

Is there a possibility to build a binary with target version 5 or 6 without these leftover strings?

**Comment by mingkuang-Chuyu** [comment]
These strings come from MS "C:\Program Files (x86)\Windows Kits\10\Source\10.0.22000.0\ucrt\internal\winapi_thunks.cpp".
> It exists in a copy in VC-LTL ：`VC-LTL5\Sources\ucrt\internal\winapi_thunks.cpp`

I optimized this file to remove unnecessary references. Change as follows:
1. remove Windows API Set.
2. remove unsed Function.

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.0.6-Beta5
