### ISSUE TITLE
5.2.3790.0编译目标在Windows Server 2003 x64上无法运行

### ISSUE THREAD

**Issue by zhangshuangjun** [Chuyu-Team/VC-LTL5#45]
程序编译成64位，VC-LTL选择5.2.3790.0，msvcrt.dll缺少一些函数，导致程序运行不起来。
目前测试发现的有tanhf，_ftime32，_gmtime32，_localtime32，文件在这里。
https://github.com/zhangshuangjun/raw_files/blob/master/msvcrt_w2003_sp2_x64.zip

[msvcrt_w2003_sp2_x64.zip](https://github.com/Chuyu-Team/VC-LTL5/files/11149653/msvcrt_w2003_sp2_x64.zip)

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.0.6-Beta5
