### ISSUE TITLE
请问MD编译方式能使用VC-LTL吗？

### ISSUE THREAD

**Issue by sinfee** [Chuyu-Team/VC-LTL5#55]
感谢开发这套非常优秀的框架！在使用说明中编译项目是采用了MT和MTd的方式。
请问对于使用MFC框架的和不使用MFC框架的项目，能不能支持使用了MD或是MDd方式编译和发布呢？
我看到VC-LTL发布版本中虽然没有MFC的库文件，但是Redist包中包含了MFC的140版本的DLL。
这是不是意味着是可以动态引入MFC呢？

**Comment by mingkuang-Chuyu** [comment]
可以，但是注意VC-LTL的那些DLL直接用的就是微软原版(仅使用ucrt完成的版本)。这个模式只能帮助你消除VCRT其他不等带来其他更多体积节省。

**Comment by mingkuang-Chuyu** [comment]
可以，但是注意VC-LTL的那些DLL直接用的就是微软原版(仅使用ucrt完成的版本)。这个模式只能帮助你消除VCRT其他不等带来其他更多体积节省。

**Comment by sinfee** [comment]
感谢支持
