### ISSUE TITLE
MFC140.dll in Redist can't run at Windows XP at 5.0.9

### ISSUE THREAD

**Issue by sinfee** [Chuyu-Team/VC-LTL5#56]
mfc140.dll or mfc140u.dll in redist can't run at Windows XP at  ver 5.0.9.
It got a error : 
Unable to locate the program input point GetTickCount64 on the dynamic link library KERNEL32.DLL

**Comment by mingkuang-Chuyu** [comment]
设计如此，XP不支持MD模式使用，因为这些dll直接使用的是微软原版。

如果需要XP下使用DLL可以考虑使用某些第三方人事编译的CRT dll。

**Comment by sinfee** [comment]
感谢，我明白了
