### ISSUE TITLE
引用std::_Tree_unchecked_const_iterator<>成员导致崩溃

### ISSUE THREAD

**Issue by lunzima** [Chuyu-Team/VC-LTL5#57]
VS2022项目，开启VC-LTL后出现该问题。
![QQ截图20231225163028](https://github.com/Chuyu-Team/VC-LTL5/assets/32062239/107058d9-c7d4-45da-8561-e1e44231b9ad)

代码没有直接引用std::_Tree_unchecked_const_iterator<>，不知道从哪里引入的该代码。
甚至pdb文件中也没有该function的符号，只能反编译看个大概。
![QQ截图20231225163319](https://github.com/Chuyu-Team/VC-LTL5/assets/32062239/bb2b5575-b38c-4a97-a43b-d83c4677e4bd)

**Comment by mingkuang-Chuyu** [comment]
如果方便建议提供dmp以及符号。如果不方便建议提供一下最小化复现代码。

**Comment by mingkuang-Chuyu** [comment]
缺少关键信息 无法进一步排查
