### ISSUE TITLE
调用std::locale(".utf8")时程序崩溃

### ISSUE THREAD

**Issue by stsm85** [Chuyu-Team/VC-LTL5#60]
auto loc = std::locale(".utf8");

使用vc-ltl编译，运行报错，不使用就不会报错

**Comment by mingkuang-Chuyu** [comment]
你好，这是设计如此。因为msvcrt.dll内部代码就不支持 UTF8的区域。

如果必须依赖此功能，那么建议在VC-LTL中开启UCRT模式。也可以不使用VC-LTL，直接使用微软原版。
> 注意：这将导致VC-LTL编译的程序依赖ucrt运行时。
