### ISSUE TITLE
C++ example InstructionSet.cpp does not run on Windows XP: LTL build imports NT6 API call

### ISSUE THREAD

**Issue by wesinator** [Chuyu-Team/VC-LTL5#62]
Example https://learn.microsoft.com/cpp/intrinsics/cpuid-cpuidex?view=msvc-170#example

The statically linked binary targeting msvcrt 5.1 (size ~62kb) does not run on NT 5.1 / Windows XP, because it still tries to load a NT6+ only API call. (https://learn.microsoft.com/windows/win32/api/winnls/nf-winnls-lcidtolocalename#requirements)
![image](https://github.com/Chuyu-Team/VC-LTL5/assets/5124946/727e6d40-c1eb-4ae6-ade6-fd00a45bbed6)
This code works if:
  - the binary is compiled with `/MD` and using the last VC runtime for XP
OR
  - statically using v141_xp and Visual C++ 2017 build toolchain (that binary is ~180kb).

Thanks,

[NO_TRAIN]::

**Comment by mingkuang-Chuyu** [comment]
please install [YY-Thunks](https://github.com/Chuyu-Team/YY-Thunks)

VC-LTL + YY-Thunks, use them together to be compatible with Windows XP.

**Comment by mingkuang-Chuyu** [comment]
In order to reduce the file size of the VC-LTL library, starting from version 5.0, VC-LTL is no longer responsible for API dependency issues. (Have you noticed that VC-LTL 5.0 is only one-tenth the size of the previous version?)

That's why we need to use YY-Thunks, which focuses on solving these API dependency problems.

**Comment by wesinator** [comment]
Thanks - I was confused because the description in the "About" section of YY-Thunks only said "XP RTM"

**Comment by mingkuang-Chuyu** [comment]
> Thanks - I was confused because the description in the "About" section of YY-Thunks only said "XP RTM"

I'm sorry that the documentation is incorrect.
