### ISSUE TITLE
api-ms-win-core-synch-l1-2-0.dll is directly depended

### ISSUE THREAD

**Issue by Xyah3PBeHB** [Chuyu-Team/VC-LTL5#66]
The following import functions are included: `WaitOnAddress`, `WakeByAddressAll` and `WakeByAddressSingle`. The target platform whether it is `6.0.6000.0` or `10.0.10240.0` has same issue.

My environment is as follows:
* Visual Studio Community 2022 17.10.2 (x64)
* MSVC 14.40.33807
* Windows Kits 10.0.22621.0

**Comment by mingkuang-Chuyu** [comment]
please install YY-Thunks.

https://github.com/Chuyu-Team/YY-Thunks?tab=readme-ov-file#21-nuget-recommend

**Comment by Xyah3PBeHB** [comment]
Thank you for the guidance. I reviewed the code. Does [this](https://github.com/Chuyu-Team/YY-Thunks/blob/45d775174d5288d438ad741eee344e46031d1840/src/Thunks/api-ms-win-core-synch.hpp#L2745) mean that this DLL is already built into Windows 8 and later operating systems?

**Comment by mingkuang-Chuyu** [comment]
Yes，STL will use win8 apis，yY-Thunks can solves this problem.


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
