### ISSUE TITLE
XP兼容模式私有内存占用异常

### ISSUE THREAD

**Issue by cxxzhang** [Chuyu-Team/VC-LTL5#67]
代码如下

#include <iostream>
#include <Windows.h>

int main()
{
    std::cout << "Hello World!\n";
    while (true) {
        Sleep(1000);
    }
}

当使用了VC-LTL5和不使用VCL-LTL5时, 内存占用相差170倍.
![C8EDB9E6CA94DC07613F0C41B7884EB8](https://github.com/user-attachments/assets/59a71262-8171-4d93-b28b-1edb35ec91be)

**Comment by mingkuang-Chuyu** [comment]
## 原因
感谢支持，我们已经定位到原因。这些内存占用来自于VC-LTL内部的全局变量。历史以来，因为Windows XP不完整支持tls
所以某些地方使用了超大全局变量模拟Tls的行为。 正因为这些全局变量导致了这些内存占用。

## 影响范围
使用XP作为编译目标编译时受到影响，可能所有VC-LTL5均受到影响。

## 修复方案
切换到tls实现，因为现在YY-thunks已经可以为XP提供完成的Tls支持。等耐心等待。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.1.1-Beta4

已经发布
