### ISSUE TITLE
 .net AOT windows server 2008 运行后没有任何反应。

### ISSUE THREAD

**Issue by sgf** [Chuyu-Team/VC-LTL5#68]
本身是  .net8.0 命令行应用程序  改成.net 8.0-windows x64 AOT发布
我安装了 VC-LTL 最新版本预览版
包括YY-Thunk最新版本预览版

使用了 <SupportedOSPlatformVersion>5.1</SupportedOSPlatformVersion> 选项

windows server 2019 上运行正常

but windows server 2008 上面 运行后没有任何反应，哪怕一个字的错误消息都没有。

![image](https://github.com/user-attachments/assets/24314ddb-26ca-4e81-ba95-9c494a173134)

发布过程中没有见到有价值的日志。
![image](https://github.com/user-attachments/assets/516d649f-a369-436e-b6e5-99f19500ab5e)

**Comment by mingkuang-Chuyu** [comment]
1. 这个同学反馈错了地方，系统兼容性问题是yY-Thunks处理的。
2. 未提供详细的问题原因。
  > 为什么程序运行没有反应，意外出错了退出了？具体设计哪个API，便于yY-Thunks进行修复。
3. 如果受限于能力，无法提供详细错误原因，请提供最小化问题复现样本代码
  > 注意：样本代码需要能正常编译，并且能复现问题。

如果无法提供详上述信息我们无法进一步处理。毕竟仅通过问题描述是无法解决问题的。

**Comment by sgf** [comment]
好。晚点，我尝试构造一下，如果可以轻易构造和复现的话。
