### ISSUE TITLE
要不要考虑搞个大的。比如搞个ReactOS的分支。然后改他的兼容层。形成一个更好的兼容windows的系统分支。

### ISSUE THREAD

**Issue by sgf** [Chuyu-Team/VC-LTL5#69]
感觉 chuyu团队的实力很强啊。如果搞好了大有可为。
为什么要做标题这件事情呢?
1.windows 系统本身发展不太成功。
2.windows-server 一定程度上已经缺乏竞争力。

尤其是第二点。如果做好了的话。感觉可以替代windows-server了。

公司名字 我都给你们想好了。初雨...公司
系统就叫初雨OS=ChuYuOS

**Comment by mingkuang-Chuyu** [comment]
很抱歉，暂不考虑做这些事情。
如果你有兴趣可以尝试一下。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: well.james ***@***.***>
Sent: Friday, November 8, 2024 6:12:16 PM
To: Chuyu-Team/VC-LTL5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Chuyu-Team/VC-LTL5] 要不要考虑搞个大的。比如搞个ReactOS的分支。然后改他的兼容层。形成一个更好的兼容windows的系统分支。 (Issue #69)


感觉 chuyu团队的实力很强啊。如果搞好了大有可为。
为什么要做标题这件事情呢?
1.windows 系统本身发展不太成功。
2.windows-server 一定程度上已经缺乏竞争力。

尤其是第二点。如果做好了的话。感觉可以替代windows-server了。

―

**Comment by sgf** [comment]
尊重
