### ISSUE TITLE
VC-LTL FH4 x64 嵌套 try catch 下无法正确抓取异常

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/VC-LTL5#8]
和鸭子探讨解决 https://github.com/Chuyu-Team/VC-LTL5/issues/7 的时候，虽然 Debug 版 NanaZip 在对应场景下不再崩溃，但 Release 版依旧在对应场景存在崩溃问题，经调查，在嵌套 try catch 的场景下 x64 版本的 VC-LTL 无法正确抓取异常。

毛利

**Comment by mingkuang-Chuyu** [comment]
4.X版本也存在此问题，说明是历史问题。

### 最小复现代码
```cpp
	try
	{
	
		try
		{
		

			throw 20190820;
		}
		catch (...)
		{
			printf("123");
		}
	}
	catch (...)
	{
		return E_OUTOFMEMORY;
	}
	printf("456");
```
